### ISSUE TITLE
Explain the purpose of this repository and how it will work.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-auth-fastly#1]

**Comment by MarquiseRosier** [comment]
@tripodsan we were talking about how any action that authenticates against fastly must use this piece of code 

async function authFastly(token, service) {
  // verify Fastly credentials
  const Fastly = await initfastly(token, service);
  await Fastly.getVersions();
  return true;
}

and we definitely want to abstract this away before it becomes a maintenance headache!

**Comment by trieloff** [comment]
We would use this with `wrap()` in `helix-perf`, `helix-publish`, `helix-logging`, and (without the wrapper, because authentication is conditional) in `helix-run-query`

**Comment by trieloff** [comment]
@MarquiseRosier it might be a good idea to start writing the usage documentation in `README.md` before we start the implementation.

**Comment by tripodsan** [comment]
hmm, I read the readme multiple times, and I still don't understand it :-)

- please use proper javascript code
- explain where the authentication gets the credentials from
- provide an example using openwhisk action utils wrap: https://github.com/adobe/openwhisk-action-utils#module_wrap

**Comment by MarquiseRosier** [comment]
@tripodsan  checkout the README in the following branch? It's a bit more clear, and fleshed out. 

https://github.com/adobe/helix-auth-fastly/tree/build-fastly-auth

**Comment by tripodsan** [comment]
> @tripodsan checkout the README in the following branch? It's a bit more clear, and fleshed out.

it looks identical to the master branch :-)

**Comment by MarquiseRosier** [comment]
@tripodsan 

Depending on the code that needs to be fastly-authenticated. If a wsk action is wrapped with it; then they'll have to send them as part of the request params; if the authFastly function is used; then it'll be somewhere in the invoking code! 

it would look something like, 

wrap(openwhisk)
.with(fastlyAuthWrapper)
.with(someOtherWrapper)(params)

**Comment by MarquiseRosier** [comment]
IF the first README is causing confusion; it's because i was pretty confused about how it would look. But I can see clearly now the rain is gone!

**Comment by tripodsan** [comment]
thanks!
